const featuredAnime = {
  "TV": [
    {
      "picture": "https://i.pinimg.com/736x/c0/82/6b/c0826bb92b789e7aa26c6de2fe4a2301.jpg",
      "synopsis": "Monkey D. Luffy refuses to let anyone or anything stand in the way of his quest to become the king of all pirates with his crew of fellow pirates.",
      "licensor": "",
      "title": "One Piece",
      "link": "https://myanimelist.net/anime/21/One_Piece",
      "genres": ["Action", "Adventure", "Fantasy"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.72",
      "members": "",
      "id": "1satgs",
      "trailerLink": "X3CR6L9uLd4"
    },
    {
      "picture": "https://i.pinimg.com/474x/76/c6/91/76c6914321296127081043375773092b.jpg",
      "synopsis": "Tanjiro sets out on a dangerous journey to find a cure for his sister and avenge his family.",
      "licensor": "",
      "title": "Kimetsu no Yaiba",
      "link": "https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
      "genres": ["Action", "Demons", "Historical", "Supernatural"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.57",
      "members": "",
      "id": "22w3r",
      "trailerLink": "nKS3mF_D7dM"
    },
    {
      "picture": "https://i.pinimg.com/736x/c0/de/28/c0de28faaeab08db023b44161b30d81c.jpg",
      "synopsis": "Eren Yeager vowed to take revenge on the Titans who destroyed his hometown and killed his mother.",
      "licensor": "",
      "title": "Shingeki no Kyojin",
      "link": "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
      "genres": ["Action", "Drama", "Fantasy", "Military", "Mystery", "Super Power"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.54",
      "members": "",
      "id": "3w3f",
      "trailerLink": "MGRm4IzK1SQ"
    },
    {
      "picture": "https://i.pinimg.com/736x/09/ed/11/09ed114bdb0f9e48da7cee86d68d83c3.jpg",
      "synopsis": "A young man named Gon Freecss aspires to become a Hunter, an elite who can track down treasures, animals, and even individuals.",
      "licensor": "",
      "title": "Hunter x Hunter (2011)",
      "link": "https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011",
      "genres": ["Action", "Adventure", "Fantasy", "Shounen", "Super Power"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "9.05",
      "members": "",
      "id": "4w4te",
      "trailerLink": "d6kBeJjTGnY"
    },
    {
      "picture": "https://i.pinimg.com/474x/4b/6d/f0/4b6df00579d31225ff5f96031002707c.jpg",
      "synopsis": "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
      "licensor": "",
      "title": "Naruto: Shippuuden",
      "link": "https://myanimelist.net/anime/1735/Naruto_Shippuuden",
      "genres": ["Action", "Comedy", "Martial Arts", "Super Power"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.18",
      "members": "",
      "id": "5weyg",
      "trailerLink": "Cw_Pz20SJX0&pp=0gcJCdgAo7VqN5tD"
    },
    {
      "picture": "https://i.pinimg.com/474x/4b/ea/e5/4beae5d20657dca3eb6a38cb6f4b6767.jpg",
      "synopsis": "High school student Yuji Itadori, who indulges in gratuitous acts of kindness for his own reasons, finds himself saving a classmate from a curse.",
      "licensor": "",
      "title": "Jujutsu Kaisen",
      "link": "https://myanimelist.net/anime/40748/Jujutsu_Kaisen",
      "genres": ["Action", "Demons", "Supernatural"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.63",
      "members": "",
      "id": "6wegw",
      "trailerLink": "pkKu9hLT-t8"
    },
    {
      "picture": "https://i.pinimg.com/736x/9e/b2/05/9eb2056467603b2e58ea9aba3008094b.jpg",
      "synopsis": "After an encounter with the most feared pirate, Red-Haired Shanks, Luffy sets off on a journey to become the Pirate King.",
      "licensor": "",
      "title": "One Piece Film: Red",
      "link": "https://myanimelist.net/anime/49820/One_Piece_Film_Red",
      "genres": ["Action", "Adventure", "Fantasy"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.14",
      "members": "",
      "id": "7dth",
      "trailerLink": "X3CR6L9uLd4"
    },
    {
      "picture": "https://i.pinimg.com/474x/a6/b7/98/a6b798c04805ab2594c60ed86346a8bc.jpg",
      "synopsis": "After losing his home, Thorfinn joins the band of Vikings responsible, hoping to find a chance to take revenge.",
      "licensor": "",
      "title": "Vinland Saga Season 2",
      "link": "https://myanimelist.net/anime/49197/Vinland_Saga_Season_2",
      "genres": ["Action", "Adventure", "Drama", "Historical"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "9.09",
      "members": "",
      "id": "8wrt",
      "trailerLink": "f8JrZ7Q_p-8"
    },
    {
      "picture": "https://i.pinimg.com/474x/3a/0b/d6/3a0bd643662d769bae3b0a349aa409e4.jpg",
      "synopsis": "Eren Yeager vowed to take revenge on the Titans who destroyed his hometown and killed his mother. This is the final season.",
      "licensor": "",
      "title": "Shingeki no Kyojin: The Final Season",
      "link": "https://myanimelist.net/anime/40028/Shingeki_no_Kyojin__The_Final_Season",
      "genres": ["Action", "Drama", "Fantasy", "Military", "Mystery", "Super Power"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.73",
      "members": "",
      "id": "9ert",
      "trailerLink": "MGRm4IzK1SQ"
    },
    {
      "picture": "https://i.pinimg.com/736x/97/73/25/977325a85efc3df0e73b79dbc0e65cda.jpg",
      "synopsis": "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage.",
      "licensor": "",
      "title": "Naruto",
      "link": "https://myanimelist.net/anime/20/Naruto",
      "genres": ["Action", "Comedy", "Martial Arts", "Super Power"],
      "producers": [""],
      "fromType": "",
      "nbEp": "",
      "releaseDate": "",
      "score": "8.08",
      "members": "",
      "id": "10weg",
      "trailerLink": "Cw_Pz20SJX0&pp=0gcJCdgAo7VqN5tD"
    },
  ],
};

export default featuredAnime