const playlistAnime = {
  "TV": [
    {
      "picture": "https://i.pinimg.com/736x/74/1b/92/741b92feca0f02de244f9e056b1e41e7.jpg",
      "synopsis": "The story follows the journey of Thorfinn, the son of one of the Viking's greatest warriors, as he seeks revenge for his father's death.",
      "licensor": "",
      "title": "Vinland Saga",
      "link": "https://myanimelist.net/anime/37521/Vinland_Saga",
      "genres": ["Action", "Adventure", "Drama", "Historical", "Seinen"],
      "producers": [""],
      "fromType": "",
      "nbEp": 24, // First season, second season has 24 as well
      "releaseDate": 2019,
      "score": "8.74",
      "members": "",
      "id": "11we4t",
      "trailerLink": "f8JrZ7Q_p-8"
    },
    {
      "picture": "https://i.pinimg.com/736x/5c/3f/a5/5c3fa580e64cab2a4bbd5ac38b8453fc.jpg",
      "synopsis": "High school student Yuji Itadori, who indulges in gratuitous acts of kindness for his own reasons, finds himself saving a classmate from a curse.",
      "licensor": "",
      "title": "Jujutsu Kaisen",
      "link": "https://myanimelist.net/anime/40748/Jujutsu_Kaisen",
      "genres": ["Action", "Demons", "Supernatural"],
      "producers": [""],
      "fromType": "",
      "nbEp": 24, // first season, second season has 23
      "releaseDate": 2020,
      "score": "8.63",
      "members": "",
      "id": "1234tg",
      "trailerLink": "pkKu9hLT-t8"
    },
    {
      "picture": "https://i.pinimg.com/736x/83/4d/6d/834d6d1242e141d6f68aca941eb61c91.jpg",
      "synopsis": "The story follows the adventures of Saitama, an incredibly powerful hero who easily defeats monsters with a single punch, but is bored due to the lack of challenge.",
      "licensor": "",
      "title": "One Punch Man",
      "link": "https://myanimelist.net/anime/30276/One_Punch_Man",
      "genres": ["Action", "Comedy", "Parody", "Sci-Fi", "Super Power", "Supernatural"],
      "producers": [""],
      "fromType": "",
      "nbEp": 12, // first season, second season has 12 as well
      "releaseDate": 2015,
      "score": "8.57",
      "members": "",
      "id": "1343y4t",
      "trailerLink": "C0M93res8Z0"
    },
    {
      "picture": "https://i.pinimg.com/736x/8c/d9/0e/8cd90ed646e10dd79c5956886e0d2316.jpg",
      "synopsis": "In a world where C.E. 71 is in full swing, a group of young Coordinators known as Serpent Tail are trying to survive. They are a group of mercenaries who are willing to do anything for money.",
      "licensor": "",
      "title": "Code Geass: Hangyaku no Lelouch",
      "link": "https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch",
      "genres": ["Action", "Military", "Sci-Fi", "Super Power", "Drama"],
      "producers": [""],
      "fromType": "",
      "nbEp": 25, // First season
      "releaseDate": 2006,
      "score": "8.71",
      "members": "",
      "id": "1434wt",
      "trailerLink": "KVqmEV3evbc"
    },
    {
      "picture": "https://i.pinimg.com/736x/41/6d/aa/416daa2c86aa835cc72bbaa3c0227556.jpg",
      "synopsis": "A group of misfits finds themselves aboard a spaceship called the Bebop, chasing criminals while dealing with their own troubled pasts.",
      "licensor": "",
      "title": "Cowboy Bebop",
      "link": "https://myanimelist.net/anime/1/Cowboy_Bebop",
      "genres": ["Action", "Adventure", "Comedy", "Drama", "Sci-Fi", "Space"],
      "producers": [""],
      "fromType": "",
      "nbEp": 26,
      "releaseDate": 1998,
      "score": "8.77",
      "members": "",
      "id": "24ert",
      "trailerLink": "AJKEXDKBVdk"
    },
    {
      "picture": "https://i.pinimg.com/736x/19/5b/21/195b21515f13aff8d74fab2052b2f5b1.jpg",
      "synopsis": "Edward and Alphonse Elric, two young alchemists, seek the Philosopher's Stone to restore their bodies after a failed alchemy experiment.",
      "licensor": "",
      "title": "Fullmetal Alchemist: Brotherhood",
      "link": "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood",
      "genres": ["Action", "Adventure", "Drama", "Fantasy", "Magic", "Military", "Shounen"],
      "producers": [""],
      "fromType": "",
      "nbEp": 64,
      "releaseDate": 2009,
      "score": "9.14",
      "members": "",
      "id": "353f",
      "trailerLink": "35cs5zFr2h8"
    },
    {
      "picture": "https://i.pinimg.com/736x/23/c5/df/23c5df70d43f186ac715a5a796e7b983.jpg",
      "synopsis": "Denji is a teenage boy who's living a bottom-of-the-barrel life as he works with a Chainsaw Devil named Pochita. One day, as Denji was living his miserable life, he got betrayed. Consequently, he died.",
      "licensor": "",
      "title": "Chainsaw Man",
      "link": "https://myanimelist.net/anime/44511/Chainsaw_Man",
      "genres": ["Action", "Demons", "Supernatural", "Horror"],
      "producers": [""],
      "fromType": "",
      "nbEp": 12,
      "releaseDate": 2022,
      "score": "8.57",
      "members": "",
      "id": "15v4t",
      "trailerLink": "l96zmDlWCBk&t=0m33s" // 
    },
    {
      "picture": "https://i.pinimg.com/736x/75/46/76/7546766d79782018898f9fa473e25b08.jpg",
      "synopsis": "A shinigami, as a god of death, can kill anyone—provided they see their victim's face and write their victim's name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm.",
      "licensor": "",
      "title": "Death Note",
      "link": "https://myanimelist.net/anime/1535/Death_Note",
      "genres": ["Mystery", "Police", "Psychological", "Supernatural", "Thriller"],
      "producers": [""],
      "fromType": "",
      "nbEp": "24",
      "releaseDate": "",
      "score": "8.63",
      "members": "",
      "id": "1635y6",
      "trailerLink": "NlJZ-YgAt-c" // 
    },
    {
      "picture": "https://i.pinimg.com/474x/41/dc/27/41dc27ceb43a7ffab1de3037f809dd81.jpg",
      "synopsis": "The story follows the journey of Frieren, an elven mage, and her companions as they embark on a journey after the defeat of the Demon King.",
      "licensor": "",
      "title": "Sousou no Frieren",
      "link": "https://myanimelist.net/anime/52991/Sousou_no_Frieren",
      "genres": ["Adventure", "Fantasy", "Slice of Life"],
      "producers": [""],
      "fromType": "",
      "nbEp": "35",
      "releaseDate": "2008",
      "score": "9.13",
      "members": "",
      "id": "17w4tr43",
      "trailerLink": "01WEqntM1NI" // 
    },
    {
      "picture": "https://i.pinimg.com/736x/81/f9/53/81f953c89ab6de06da6b5110b1d75dac.jpg",
      "synopsis": "The story follows the daily lives of various high school students with supernatural powers and abilities at a school called Hachimitsu Academy.",
      "licensor": "",
      "title": "Charlotte",
      "link": "https://myanimelist.net/anime/28999/Charlotte",
      "genres": ["Drama", "Super Power", "School"],
      "producers": [""],
      "fromType": "",
      "nbEp": "23",
      "releaseDate": "2005",
      "score": "7.82",
      "members": "",
      "id": "18etew",
      "trailerLink": "hfmRxXVvFYA" // 
    },
    {
      "picture": "https://i.pinimg.com/736x/57/ed/f9/57edf95ca245d5d76baf8a9e2d8c9fec.jpg",
      "synopsis": "The story follows the life of Sakata Gintoki, an eccentric samurai, his apprentice, Shimura Shinpachi, and a teenage alien girl named Kagura. All three are \"freelancers\" who search for odd jobs in order to pay the monthly rent, which usually goes unpaid anyway.",
      "licensor": "",
      "title": "Gintama",
      "link": "https://myanimelist.net/anime/918/Gintama",
      "genres": ["Action", "Comedy", "Historical", "Parody", "Sci-Fi", "Shounen"],
      "producers": [""],
      "fromType": "",
      "nbEp": "23",
      "releaseDate": "2020",
      "score": "9.06",
      "members": "",
      "id": "19457",
      "trailerLink": "bwvGmPyNQUE" // 
    },
  ],
};

export default playlistAnime;